update docs: config_param.md
bfenetworks/api-server pull request #22
Opened 2022-03-22 07:34 UTC by clarinette9

2022-03-22 09:56 UTC, clarinette9 commented
@mileszhang2016 @liuximu

2022-03-28 10:08 UTC, mileszhang2016 requested changes

2022-03-28 10:08 UTC, mileszhang2016 commented on docs/zh_cn/config_param.md
> +| BackupCount | Int<br>日志删除前轮转次数，即最大的日志存储数量              |
日志删除前轮转次数，即最大的日志存储数量 => 最大日志文件备份数，即轮转删除日志前最大的日志文件数量（注：每次日志轮转都会产生一个新的日志文件。在超过BackupCount后，要删除最老的日志文件）

2022-03-28 10:08 UTC, mileszhang2016 commented on docs/zh_cn/config_param.md
> +| GracefulTimeOutMs | Int<br>API Server关闭时的优雅退出时间，单位为毫秒 |
GracefulTimeOutMs => GracefulTimeOutInMs

2022-03-28 10:08 UTC, mileszhang2016 commented on docs/zh_cn/config_param.md
> +| ConnMaxIdleTimeMs    | Int<br>连接最大空闲时间，单位为毫秒                          |
=》ConnMaxIdleTimeInMs

2022-03-28 10:08 UTC, mileszhang2016 commented on docs/zh_cn/config_param.md
> +| ConnMaxLifetimeMs    | Int<br>连接最大生命期，单位为毫秒                            |
=》ConnMaxLifetimeInMs

2022-03-28 10:08 UTC, mileszhang2016 commented on docs/zh_cn/config_param.md
> +| SessionExpireDay  | Int<br>会话过期时间，单位为天                                |
=》SessionExpireTimeInDay

2022-04-15 08:15 UTC, merged